#!/bin/bash

#sbatch --mem=100g --time=24:00:00 run_TWAS.sh
#example of one cell type, this was run for all 33 tested cell types
module load plink/1.9.0-beta4.4
module load GCTA
module load gemma
module load R

Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 1 --out Adv_fib.Shi.lung.1.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 2 --out Adv_fib.Shi.lung.2.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 3 --out Adv_fib.Shi.lung.3.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 4 --out Adv_fib.Shi.lung.4.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 5 --out Adv_fib.Shi.lung.5.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 6 --out Adv_fib.Shi.lung.6.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 7 --out Adv_fib.Shi.lung.7.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 8 --out Adv_fib.Shi.lung.8.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 9 --out Adv_fib.Shi.lung.9.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 10 --out Adv_fib.Shi.lung.10.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 11 --out Adv_fib.Shi.lung.11.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 12 --out Adv_fib.Shi.lung.12.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 13 --out Adv_fib.Shi.lung.13.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 14 --out Adv_fib.Shi.lung.14.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 15 --out Adv_fib.Shi.lung.15.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 16 --out Adv_fib.Shi.lung.16.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 17 --out Adv_fib.Shi.lung.17.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 18 --out Adv_fib.Shi.lung.18.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 19 --out Adv_fib.Shi.lung.19.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 20 --out Adv_fib.Shi.lung.20.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 21 --out Adv_fib.Shi.lung.21.dat
Rscript /data/Choi_lung/TTL/FUSION/fusion_twas-master/FUSION.assoc_test.R --sumstats /data/Choi_lung/TTL/FUSION/Shi_GWAS/Shi_EAS.sumstats.gz --weights Adv_fib.pos --weights_dir ./WEIGHTS/ --ref_ld_chr /data/Choi_lung/TTL/FUSION/Shi_GWAS/FLCCA_plink/FLCCA_1kg. --chr 22 --out Adv_fib.Shi.lung.22.dat
